### ISSUE TITLE
PiP an entire screen?

### ISSUE THREAD

**Issue by sinedied** [amitv87/PiP#10]
First, let me say a big THANK YOU for this tool! It makes my life so much easier for giving live stream presentations, as I can share whatever window I want in it and keep full control of what's visible.

Do you think that would be possible to also PiP an entire screen instead of a given window? That would be perfect for demos.

**Comment by amitv87** [comment]
Available in the latest [release](https://github.com/amitv87/PiP/releases/tag/v2.11).
