### ISSUE TITLE
What does the top right pin sign do? 

### ISSUE THREAD

**Issue by shuangg** [amitv87/PiP#13]
What does the top-right pin do?  
![image](https://user-images.githubusercontent.com/416595/116565969-3d632780-a8fe-11eb-8a52-cc1dda4a9546.png)

**Comment by amitv87** [comment]
It makes the window join all spaces (desktops).

**Comment by muescha** [comment]
i don't understand the explanation - and i see no change while i select and deselect the pin

**Comment by amitv87** [comment]
> i don't understand the explanation - and i see no change while i select and deselect the pin

Try switching workspace/desktop with/without pinning the pip window and you will get to know.
