### ISSUE TITLE
M1 gives black screen

### ISSUE THREAD

**Issue by DUOLabs333** [amitv87/PiP#14]
When I tried to use it on Sublime, it just showed a black screen.

**Comment by amitv87** [comment]
Away from mac for some time!
Also do not have an M1

**Comment by huyz** [comment]
@DUOLabs333 Should have left this open for other users to see

**Comment by JohnLockeNJ** [comment]
I have the same problem. Using PIP on my M1 Mac gives me a black screen whereas it worked fine on my Intel Mac.
