### ISSUE TITLE
Sort of window list/presentation

### ISSUE THREAD

**Issue by moshed** [amitv87/PiP#22]
Not sure how the windows are sorted but it doesn't seem alphabetical or recent usage. Either way I think having each app  with an expandable list of the app would look much neater similar not sure if im explaining myself clearly but I envision something like finders view below 
<img width="158" alt="image" src="https://user-images.githubusercontent.com/8683379/173729153-5f4c2690-2747-4a7e-9d27-de7273f59654.png">
![image](https://user-images.githubusercontent.com/8683379/173728858-91eb90d4-8d9d-455f-9942-6b557c14a146.png)

**Comment by amitv87** [comment]
https://github.com/amitv87/PiP/issues/20#issuecomment-1156171321
