### ISSUE TITLE
Does not work in OSX 10.12.6 (16G2136) (Sierra)

### ISSUE THREAD

**Issue by drorthoman** [amitv87/PiP#24]
I couldn't make it work on Sierra 10.12.6. App doesn't open at all.
What should i do?

**Comment by drorthoman** [comment]
Which version is last to work on Sierra?

**Comment by amitv87** [comment]
I am not sure, which version would work. Just by looking at the os release date, I think the very [first release](https://github.com/amitv87/PiP/releases/tag/1.0) should work.
You may try cloning the repo and debugging app using xcode to find the root cause of the reported issue.
