### ISSUE TITLE
Setting to make it not always on top?

### ISSUE THREAD

**Issue by dchuk** [amitv87/PiP#25]
This app is exactly what I was looking for as a fast, free, simple screen mirroring app to put my iPad screen on my mac (for real-time sketching and writing on my iPad to be visible on Zoom calls for example).

Is it possible to make it so that there's a setting to toggle so the app window isn't always on top? I want to be able to toggle to other windows easily as I'm working. I can try and work on the code myself but I'm not well versed in mac app development.

Great job on this!

**Comment by amitv87** [comment]
I have enabled the always on top option and published it in [release v2.41](https://github.com/amitv87/PiP/releases/tag/v2.41).
But there's a small glitch in the way nspanel behaves because of which non floating panels move to background on using exposé or switching workspace.
