### ISSUE TITLE
works but resolution looks like 360p ?

### ISSUE THREAD

**Issue by avichou** [amitv87/PiP#27]
it works for me , but for some reason it looks like 240/360p, which makes it very hard to read text (in my case i mostly need it to check chrome task manager ) 

<img width="1440" alt="image" src="https://github.com/amitv87/PiP/assets/86660671/b59b407b-c588-4896-8082-fe4c34016b7c">

**Comment by amitv87** [comment]
Support for hidpi (retina displays) is available in the [latest release](https://github.com/amitv87/PiP/releases/tag/v2.50).
It can be enabled from the preferences and comes in to affect for new pip windows.

**Comment by avichou** [comment]
> Support for hidpi (retina displays) is available in the [latest release](https://github.com/amitv87/PiP/releases/tag/v2.50). It can be enabled from the preferences and comes in to affect for new pip windows.

thank you ! it's MUCH better but still not as good as native window, especially fonts and text , they still look blurry and low res to me (close to 720p+ i'd say)

**Comment by zackify** [comment]
yeah same, text is fuzzy. its a shame macos doesnt let you full screen content to a small portion of a window, this is as close as i can get
