### ISSUE TITLE
Quick Show/Hide

### ISSUE THREAD

**Issue by z0oinks** [amitv87/PiP#3]
Another feature request from OnTopReplica: a keyboard shortcut to quickly hide or show the overlay

**Comment by fxjkhr** [comment]
So I found a half-solution:  
1. Bring up the Command-Tab Application Switcher
2. Use Command+H Hide on PiP within the Application Switcher

**Comment by amitv87** [comment]
cmd+h is now implemented! https://github.com/amitv87/PiP/commit/e92579e6a8589ad7dadc3f155e41b33e02bc6173
