### ISSUE TITLE
Sonoma 14.4 permissions are broken

### ISSUE THREAD

**Issue by ZeekWorld** [amitv87/PiP#33]
On MacOS Sonoma 14.4 permissions are broken for the last two builds, 2.50 is the last working version.
Missing ScreenCapture Permission message continues to pop up even if the permissions have already been set.

![image](https://github.com/amitv87/PiP/assets/16088952/d0f22192-d229-4b7b-b301-69ead22f11fa)

**Comment by amitv87** [comment]
Duplicate to https://github.com/amitv87/PiP/issues/26
On a side note, one can delete existing permissions as shown below and then use new PiP
<img width="353" alt="image" src="https://github.com/amitv87/PiP/assets/8436881/fd66f840-5f48-42c7-8c66-ad4ae46b7964">
