### ISSUE TITLE
Black screen on brave

### ISSUE THREAD

**Issue by juanbasay** [amitv87/PiP#34]
When i change between desktops, it turns youtube to black. any solution?

**Comment by amitv87** [comment]
This is a known behaviour.
Many apps, especially browsers halt rendering the content when their windows are completely in background, i.e. hidden behind other windows, open in desktops/workspaces which are not in focus. In short these are windows which are not directly intercating with user.

In case of chromium based browsers you may find somthing in chrome://flags to change the behaviour.

There is almost nothing that the PiP can do in this regard.
