### ISSUE TITLE
Mac no longer shows up on iPhone Airplay menu when built-in AirPlay receiver is turned off

### ISSUE THREAD

**Issue by kermitkc** [amitv87/PiP#37]
Turned the built-in AirPlay receiver back on and I could connect again.  The Mac just doesn't show up in the menu on my phone, ergo it's impossible to stream AirPlay with PiP.  Maybe I'm just doing something wrong?  Bluetooth is enabled, on same wifi network, and as mentioned, it immediately works when I turn built-in AirPlay receiver back on.  "Use PiP as Airplay receiver" is turned on in PiP's preferences.
MacBook Air 2020, Ventura 13.6 and iPhone 14, iOS 17.4.1

**Comment by amitv87** [comment]
PiP's airplay receiver only needs proper i/p network, it does not support any other network like bluetooth. You just need to make sure that your apple devices are on the same local network. Network configuration/stability also affects the discovery process which uses [bonjour](https://en.wikipedia.org/wiki/Bonjour_(software)). You may use tools like https://apps.apple.com/us/app/discovery-dns-sd-browser/id305441017 and https://play.google.com/store/apps/details?id=de.wellenvogel.bonjourbrowser&hl=en_IN&gl=US to check if PiP airplay service is discoverable over you network.
