### ISSUE TITLE
Request: Native macOS Picture-in-Picture

### ISSUE THREAD

**Issue by flipsticks** [amitv87/PiP#4]
Hey amitv87,

Are there any plans to support Apples implementation of PiP? (Where the window float across multiple desktops/fullscreen apps, pinned to the screen edge)

**Comment by amitv87** [comment]
By Apples implementation of PiP do you mean [split view](https://support.apple.com/kb/PH25072?locale=en_US)

**Comment by amitv87** [comment]
Unfortunately PiP apis are not public yet.
Though there's a [way](https://github.com/steve228uk/PiPHack) to use it, I think it is only meant for video playback from the web/local file.

**Comment by maxnowack** [comment]
In his [blog post](https://stephenradford.me/hacking-macos-sierras-pip/) about the hack, he mentioned that any view controller can be displayed in the pip window. So maybe it's possible :)
> * ANY view controller — not just video — can be displayed but the play/pause button cannot be removed or hidden (at least not via any accessible method).

**Comment by amitv87** [comment]
Interesting, will give a try :)

**Comment by maxnowack** [comment]
@amitv87 any news on this? :)

**Comment by amitv87** [comment]
I did try it but the end result was very flaky. Resizing the source window resulted in corrupt aspect ratio.

Also I feel that Apple's implementation has a feature which is missing in my implementation, i.e. the preview window remains pinned even when switching to full screen app / desktop.
I'm trying to get this one to work

**Comment by amitv87** [comment]
> @amitv87 any news on this? :)
https://github.com/amitv87/PiP/tree/nativePiP
That's what I could do.

**Comment by amitv87** [comment]
Closing this :)

**Comment by amitv87** [comment]
Closing this :)
