### ISSUE TITLE
Right click isn't functioning.

### ISSUE THREAD

**Issue by themanro** [amitv87/PiP#8]
For some reason right-clicking in the window isn't producing any dialogs. I've tried to dig into Privacy access in settings, but not seeing PiP listed anywhere to allow access. Running 10.15.4

**Comment by amitv87** [comment]
When **click though** mode is enabled, pip windows do not respond to mouse events.

**Comment by themanro** [comment]
I made sure it is disabled, still have an issue where right-clicking in the window doesn't do anything.

**Comment by amitv87** [comment]
@themanro  Any steps to reproduce? Works fine for me.

**Comment by billfroelich** [comment]
I'm on 10.15.7 and am also not seeing this issue.  I did see the list not populating the window titles correctly until I granted the correct permissions (screen recording) but I would consider that an expected behavior
