### ISSUE TITLE
Add double-click on pip window to bring app to front

### ISSUE THREAD

**Issue by billfroelich** [amitv87/PiP#9]
When using PiP to monitor a meeting or watching a video if I need to interact with that window I have to go find it either from my dock or alt-tab.  It would be nice if I could just double-click on the pip window to bring it to the front.  Is this something that might be possible to implement?

**Comment by amitv87** [comment]
Added the feature in this commit
https://github.com/amitv87/PiP/commit/267dcb6d1fb11eefba8eb5095dd51629dddb7d02

**Comment by billfroelich** [comment]
Pulled and built locally. Works great!  Thanks for adding this in.
